[package]
resolver = "2"
name = "mylib"
version = "0.1.0"
edition = "2021"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[lib]
name = "mylib"
crate-type = ["staticlib"]

[build-dependencies]
cbindgen = "0.24.0"

[dependencies]
cty = "0.2.2"
heapless = "0.8.0"
